import 'dart:async';

import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../services/auth_service.dart';
import 'app_screen.dart';

const authAccent = Color(0xFF3DDC97);
const authBackground = Color(0xFF0B1714);
const authSurface = Color(0xFF14231F);

class AuthGate extends StatelessWidget {
  const AuthGate({super.key});
  @override Widget build(BuildContext context) => AuthService.instance.currentUser == null ? const LoginScreen() : const AppScreen();
}

class AuthScaffold extends StatelessWidget {
  const AuthScaffold({required this.child, super.key});
  final Widget child;
  @override Widget build(BuildContext context) => Scaffold(backgroundColor: authBackground, body: SafeArea(child: Center(child: SingleChildScrollView(padding: const EdgeInsets.all(24), child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 480), child: child)))));
}

class AuthHeader extends StatelessWidget {
  const AuthHeader({required this.title, required this.subtitle, super.key});
  final String title, subtitle;
  @override Widget build(BuildContext context) => Column(children: [Image.asset('lib/assets/manga_lord_logo.png', width: 86, height: 58, fit: BoxFit.contain), const SizedBox(height: 18), const Text('Manga Lord', style: TextStyle(color: Colors.white, fontSize: 30, fontWeight: FontWeight.w900)), const SizedBox(height: 28), Text(title, style: const TextStyle(color: Colors.white, fontSize: 25, fontWeight: FontWeight.w800)), const SizedBox(height: 8), Text(subtitle, textAlign: TextAlign.center, style: const TextStyle(color: Colors.white70))]);
}

class AuthInput extends StatelessWidget {
  const AuthInput({required this.controller, required this.label, this.obscure = false, this.keyboardType, this.validator, this.toggle, super.key});
  final TextEditingController controller; final String label; final bool obscure; final TextInputType? keyboardType; final String? Function(String?)? validator; final VoidCallback? toggle;
  @override Widget build(BuildContext context) => Padding(padding: const EdgeInsets.only(bottom: 14), child: TextFormField(controller: controller, obscureText: obscure, keyboardType: keyboardType, validator: validator, style: const TextStyle(color: Colors.white), decoration: InputDecoration(labelText: label, labelStyle: const TextStyle(color: Colors.white70), filled: true, fillColor: authSurface, suffixIcon: toggle == null ? null : IconButton(onPressed: toggle, icon: Icon(obscure ? Icons.visibility_rounded : Icons.visibility_off_rounded, color: Colors.white70)), border: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide.none))));
}

class LoginScreen extends StatefulWidget { const LoginScreen({super.key}); @override State<LoginScreen> createState() => _LoginScreenState(); }
class _LoginScreenState extends State<LoginScreen> {
  final form = GlobalKey<FormState>(); final email = TextEditingController(); final password = TextEditingController(); bool busy = false, obscure = true; String? error;
  Future<void> _submit() async { if (!form.currentState!.validate()) return; setState(() { busy = true; error = null; }); try { await AuthService.instance.signIn(email: email.text, password: password.text); if (mounted) Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const AppScreen())); } on AuthException catch (e) { if (mounted) setState(() => error = _authError(e)); } finally { if (mounted) setState(() => busy = false); } }
  Future<void> _google() async { setState(() { busy = true; error = null; }); try { await AuthService.instance.signInWithGoogle(); if (mounted) Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const AppScreen())); } on AuthException catch (e) { if (mounted) setState(() => error = _authError(e)); } finally { if (mounted) setState(() => busy = false); } }
  @override Widget build(BuildContext context) => AuthScaffold(child: Form(key: form, child: Column(children: [const AuthHeader(title: 'Welcome Back', subtitle: 'Sign in to continue to Manga Lord'), const SizedBox(height: 30), AuthInput(controller: email, label: 'Email', keyboardType: TextInputType.emailAddress, validator: (v) => v != null && v.contains('@') ? null : 'Enter a valid email'), AuthInput(controller: password, label: 'Password', obscure: obscure, toggle: () => setState(() => obscure = !obscure), validator: (v) => v != null && v.length >= 6 ? null : 'Password must be at least 6 characters'), Align(alignment: Alignment.centerRight, child: TextButton(onPressed: busy ? null : () => Navigator.push(context, MaterialPageRoute(builder: (_) => const ForgotPasswordScreen())), child: const Text('Forgot Password?'))), if (error != null) ErrorText(error!), const SizedBox(height: 8), SizedBox(width: double.infinity, child: FilledButton(onPressed: busy ? null : _submit, child: busy ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2)) : const Text('Sign In'))), const SizedBox(height: 10), SizedBox(width: double.infinity, child: OutlinedButton.icon(onPressed: busy ? null : _google, icon: const Icon(Icons.login), label: const Text('Continue with Google'))), const SizedBox(height: 8), TextButton(onPressed: busy ? null : () => Navigator.push(context, MaterialPageRoute(builder: (_) => const SignUpScreen())), child: const Text("Don't have an account? Sign Up")), TextButton(onPressed: busy ? null : () => Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const AppScreen())), child: const Text('Continue without an account'))])));
}

class SignUpScreen extends StatefulWidget { const SignUpScreen({super.key}); @override State<SignUpScreen> createState() => _SignUpScreenState(); }
class _SignUpScreenState extends State<SignUpScreen> {
  final form = GlobalKey<FormState>(); final username = TextEditingController(); final email = TextEditingController(); final password = TextEditingController(); final confirm = TextEditingController(); bool busy = false, obscure = true; String? error;
  Future<void> _submit() async { if (!form.currentState!.validate()) return; setState(() { busy = true; error = null; }); try { await AuthService.instance.signUp(username: username.text, email: email.text, password: password.text); if (!mounted) return; if (AuthService.instance.currentUser == null) { setState(() => error = 'Account created. Check your email, verify your account, then sign in.'); } else { Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const AppScreen())); } } on AuthException catch (e) { if (mounted) setState(() => error = _authError(e)); } finally { if (mounted) setState(() => busy = false); } }
  @override Widget build(BuildContext context) => AuthScaffold(child: Form(key: form, child: Column(children: [const AuthHeader(title: 'Create Account', subtitle: 'Create your Manga Lord account'), const SizedBox(height: 30), AuthInput(controller: username, label: 'Username', validator: (v) => v == null || v.trim().length < 2 ? 'Enter a username' : null), AuthInput(controller: email, label: 'Email', keyboardType: TextInputType.emailAddress, validator: (v) => v != null && v.contains('@') ? null : 'Enter a valid email'), AuthInput(controller: password, label: 'Password', obscure: obscure, toggle: () => setState(() => obscure = !obscure), validator: (v) => v != null && v.length >= 6 ? null : 'Use at least 6 characters'), AuthInput(controller: confirm, label: 'Confirm Password', obscure: obscure, validator: (v) => v == password.text ? null : 'Passwords do not match'), if (error != null) ErrorText(error!), const SizedBox(height: 8), SizedBox(width: double.infinity, child: FilledButton(onPressed: busy ? null : _submit, child: busy ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2)) : const Text('Create Account'))), TextButton(onPressed: busy ? null : () => Navigator.pop(context), child: const Text('Already have an account? Sign In'))])));
}

class ForgotPasswordScreen extends StatefulWidget { const ForgotPasswordScreen({super.key}); @override State<ForgotPasswordScreen> createState() => _ForgotPasswordScreenState(); }
class _ForgotPasswordScreenState extends State<ForgotPasswordScreen> { final email = TextEditingController(); bool busy = false; String? message; String? error; Future<void> _send() async { setState(() { busy = true; error = null; message = null; }); try { await AuthService.instance.sendReset(email.text); if (mounted) setState(() => message = 'Reset link sent. Check your inbox.'); } on AuthException catch (e) { if (mounted) setState(() => error = _authError(e)); } finally { if (mounted) setState(() => busy = false); } } @override Widget build(BuildContext context) => AuthScaffold(child: Column(children: [const AuthHeader(title: 'Reset Password', subtitle: 'We will send a secure reset link to your email'), const SizedBox(height: 30), AuthInput(controller: email, label: 'Email', keyboardType: TextInputType.emailAddress), if (error != null) ErrorText(error!), if (message != null) Text(message!, style: const TextStyle(color: authAccent)), const SizedBox(height: 8), SizedBox(width: double.infinity, child: FilledButton(onPressed: busy ? null : _send, child: busy ? const CircularProgressIndicator() : const Text('Send Reset Link'))), TextButton(onPressed: () => Navigator.pop(context), child: const Text('Back to Sign In'))])); }

class VerifyEmailScreen extends StatefulWidget { const VerifyEmailScreen({super.key}); @override State<VerifyEmailScreen> createState() => _VerifyEmailScreenState(); }
class _VerifyEmailScreenState extends State<VerifyEmailScreen> { bool busy = false; String? message; Timer? timer; int cooldown = 0; @override void dispose() { timer?.cancel(); super.dispose(); } Future<void> _resend() async { if (cooldown > 0) return; setState(() { busy = true; cooldown = 30; }); await AuthService.instance.resendVerification(); timer = Timer.periodic(const Duration(seconds: 1), (t) { if (!mounted) return; if (cooldown <= 1) { t.cancel(); setState(() => cooldown = 0); } else setState(() => cooldown--); }); if (mounted) setState(() { busy = false; message = 'Verification email sent.'; }); } Future<void> _check() async { await AuthService.instance.reloadUser(); if (mounted) setState(() {}); } @override Widget build(BuildContext context) { final email = AuthService.instance.currentUser?.email ?? ''; return AuthScaffold(child: Column(children: [const AuthHeader(title: 'Verify Your Email', subtitle: 'Verify your email to continue to Manga Lord'), const SizedBox(height: 22), Text(email, style: const TextStyle(color: authAccent)), const SizedBox(height: 24), const Icon(Icons.mark_email_read_outlined, color: authAccent, size: 72), const SizedBox(height: 24), SizedBox(width: double.infinity, child: FilledButton(onPressed: busy || cooldown > 0 ? null : _resend, child: Text(cooldown > 0 ? 'Resend in ${cooldown}s' : 'Resend Email'))), OutlinedButton(onPressed: _check, child: const Text("I've Verified")), if (message != null) Text(message!, style: const TextStyle(color: authAccent)), TextButton(onPressed: () => AuthService.instance.signOut(), child: const Text('Back to Sign In'))])); } }

class AccountScreen extends StatefulWidget { const AccountScreen({super.key}); @override State<AccountScreen> createState() => _AccountScreenState(); }
class _AccountScreenState extends State<AccountScreen> {
  String? _profileImageUrl(User? user) => user?.userMetadata?['avatar_url'] as String?;

  String _displayName(User? user) =>
      (user?.userMetadata?['display_name'] as String?) ?? '';
 Map<String, dynamic> data = {}; bool busy = true; @override void initState() { super.initState(); _load(); } Future<void> _load() async { data = await AuthService.instance.profile(); if (mounted) setState(() => busy = false); } Future<void> _edit(String field, String title, String value) async { final controller = TextEditingController(text: value); final result = await showDialog<String>(context: context, builder: (_) => AlertDialog(title: Text(title), content: TextField(controller: controller, maxLength: field == 'bio' ? 240 : 40, maxLines: field == 'bio' ? 4 : 1), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')), FilledButton(onPressed: () => Navigator.pop(context, controller.text.trim()), child: const Text('Save'))])); if (result == null || result.isEmpty && field == 'username') return; await AuthService.instance.updateProfile(username: field == 'username' ? result : null, bio: field == 'bio' ? result : null); _load(); }   Future<void> _changePhoto() async { final picked = await FilePicker.platform.pickFiles(type: FileType.image, withData: true); final bytes = picked?.files.single.bytes; if (bytes == null || !mounted) return; setState(() => busy = true); try { await AuthService.instance.uploadProfileImage(bytes, picked!.files.single.extension ?? 'jpg'); } catch (_) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Could not upload profile picture'))); } finally { if (mounted) { await AuthService.instance.reloadUser(); setState(() => busy = false); } } }
  @override Widget build(BuildContext context) { final user = AuthService.instance.currentUser; if (busy) return const Scaffold(body: Center(child: CircularProgressIndicator())); return Scaffold(appBar: AppBar(title: const Text('Profile')), body: ListView(padding: const EdgeInsets.all(20), children: [Center(child: InkWell(onTap: _changePhoto, borderRadius: BorderRadius.circular(60), child: CircleAvatar(radius: 48, backgroundColor: authSurface, backgroundImage: (_profileImageUrl(user) == null ? const AssetImage('lib/assets/default_user_avatar.jpg') : NetworkImage(_profileImageUrl(user)!)) as ImageProvider<Object>, child: null))), const SizedBox(height: 7), const Center(child: Text('Change Profile Picture', style: TextStyle(color: authAccent))), const SizedBox(height: 12), Center(child: Text(data['displayName'] as String? ?? _displayName(user), style: const TextStyle(fontSize: 22, fontWeight: FontWeight.w800))), const SizedBox(height: 24), ListTile(title: const Text('Email'), subtitle: Text(user?.email ?? '')), ListTile(title: const Text('User ID'), subtitle: Text(user?.id ?? ''), trailing: IconButton(icon: const Icon(Icons.copy), onPressed: () => Clipboard.setData(ClipboardData(text: user?.id ?? '')))), ListTile(title: const Text('About Me'), subtitle: Text(data['bio'] as String? ?? 'No bio yet'), trailing: IconButton(icon: const Icon(Icons.edit), onPressed: () => _edit('bio', 'Edit Bio', data['bio'] as String? ?? ''))), ListTile(title: const Text('Username'), subtitle: Text(data['displayName'] as String? ?? ''), trailing: IconButton(icon: const Icon(Icons.edit), onPressed: () => _edit('username', 'Edit Username', data['displayName'] as String? ?? ''))), const SizedBox(height: 18), OutlinedButton.icon(onPressed: () async { await AuthService.instance.signOut(); if (mounted) Navigator.pushAndRemoveUntil(context, MaterialPageRoute(builder: (_) => const LoginScreen()), (_) => false); }, icon: const Icon(Icons.logout), label: const Text('Sign Out'))])); } }

 class ErrorText extends StatelessWidget { const ErrorText(this.text, {super.key}); final String text; @override Widget build(BuildContext context) => Padding(padding: const EdgeInsets.only(bottom: 10), child: Text(text, textAlign: TextAlign.center, style: const TextStyle(color: Colors.redAccent))); }
String _authError(AuthException error) { switch (error.code) { case 'user_already_exists': case 'email_exists': return 'This email is already registered.'; case 'invalid_credentials': return 'Invalid email or password.'; case 'network_error': return 'Network error. Please try again.'; default: return error.message; } }
